// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nbywqlxjgrusahygwykn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ieXdxbHhqZ3J1c2FoeWd3eWtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgyNTAwNDUsImV4cCI6MjA5MzgyNjA0NX0.7Nw0FENPahrhBmhH2USKIFrlDz2W509_aXxcyiHXzsU";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);